server:
  port: 8080
logging:
  level:
    "org.coinen.reactive.persistence": "DEBUG"
    "org.springframework.jdbc.core.JdbcTemplate": "DEBUG"
    "org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate": "DEBUG"
    "org.springframework.data.mongodb.core.ReactiveMongoTemplate": "DEBUG"
    "org.springframework.data.couchbase": "DEBUG"



# Database configurations (Postgres, Mongo, Cassandra)

spring:
  datasource:
      url: "jdbc:postgresql://localhost:5432/application"
      username: "postgres"
      password: "postgres"
      driver-class-name: "org.postgresql.Driver"
  data:
    cassandra:
      port: 9042
      keyspace-name: "reactive"
    mongodb:
      username: "mongo"
      password: "mongo"
      database: "application"

# Couchbase configuration

couchbase:
  cluster:
    host: "127.0.0.1"
    bucket: "bucket1"
    user: "Administrator"
    password: "password"



# Management section --------------------

#management:
#  server:
#    port: 8090
#  endpoints:
#    web:
#      exposure.include: "*"
#  endpoint:
#    health:
#      show-details: "always"
#      cache:
#        time-to-live: 10s